spring.datasource.url=jdbc:mysql://localhost:3306/chicken_friends?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Sanderpoli2810va
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
# ? Fecha de vencimiento del alquiler (Formato: Año-Mes-Dia hora:min:seg hora militar)
app.alquiler.fecha-vence=2026-06-27T14:31:00